providers = ["node"]

[phases.setup]
nixPkgs = ["...", "python3", "python3Packages.pip", "ffmpeg"]

[phases.installPython]
dependsOn = ["setup"]
cmds = ["python3 -m pip install yt-dlp discord.py --break-system-packages"]
